name:

on:
  workflow_call:
    inputs:
      continue-on-error:
        description: Whether to continue on job failure.
        required: false
        default: false
        type: boolean
      environment:
        description: Target deployment environment.
        required: false
        default: null
        type: string
      dry-run:
        description: Whether to just dry-run the workflow.
        required: false
        default: false
        type: boolean
      custom-tag:
        description: Custom tag to be applied to the commit.
        required: false
        default: null
        type: string
      tag-prefix:
        description: Prefix for the tag. Has no effect if 'custom-tag' is provided.
        required: false
        default: 'v'
        type: string
    outputs:
      structured:
        description: Structured output containing everything in mathieudutour/github-tag-action outputs.
        value: ${{ jobs.apply-tag.outputs }}
      tag:
        description: Tag suggested or generated by this workflow.
        value: ${{ jobs.apply-tag.outputs.tag }}
      changelog:
        description: Automatically generated changelog
        value: ${{ jobs.apply-tag.outputs.changelog }}
      outcome:
        description: The outcome of the workflow.
        value: ${{ jobs.apply-tag.result }}

jobs:
  apply-tag:
    name: ${{ inputs.custom-tag == null && 'GET' || inputs.custom-tag }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    continue-on-error: ${{ inputs.continue-on-error }}
    outputs:
      tag: ${{ steps.set-tag.outputs.new_tag }}
      changelog: ${{ steps.set-tag.outputs.changelog }}
    steps:
      - name: Apply Tag
        id: set-tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.custom-tag }}
          create_annotated_tag: true
          tag_prefix: ${{ inputs.custom-tag == null && inputs.tag-prefix || '' }}
          dry_run: ${{ inputs.dry-run }}
