name: Tagging

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: Custom tag to be applied
        required: false
        default: null
        type: string

permissions:
  contents: write
  id-token: write

concurrency:
  group: prod
  cancel-in-progress: false

jobs:
  calculate-tag:
    name: Calculate tag
    if: inputs.tag == null
    uses: ./.github/tag-tool.yml
    with:
      tag-prefix: v
      dry-run: true

  apply-tag:
    name: Apply tag
    needs: calculate-tag
    if: always()
    uses: ./.github/tag-tool.yml
    with:
      environment: tagging
      custom-tag: ${{ inputs.tag == null && needs.calculate-tag.outputs.tag || inputs.tag }}
