name: Tagging

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: Semver version without the prefixing 'v'
        required: false
        default: null
        type: string

permissions:
  contents: write
  id-token: write

concurrency:
  group: prod
  cancel-in-progress: false

jobs:
  # calculate-tag:
  #   name: Calculate tag
  #   runs-on: ubuntu-22.04
  #   outputs:
  #     tag: ${{ steps.get-tag.outputs.new_tag }}
  #   steps:
  #     - name: Calculate GitHub Tag
  #       id: get-tag
  #       uses: mathieudutour/github-tag-action@v6.1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         custom_tag: ${{ inputs.tag }}
  #         create_annotated_tag: true
  #         tag_prefix: v
  #         dry_run: true

  calculate-tag:
    name: Calculate tag
    uses: ./.github/workflows/tag-tool.yml
    with:
      tag-prefix: v
      dry-run: true

  apply-tag:
    name: Apply tag
    needs: calculate-tag
    uses: ./.github/workflows/tag-tool.yml
    with:
      continue-on-error: true
      environment: tagging
      custom-tag: ${{ needs.calculate-tag.outputs.tag }}

  # apply-tag:
  #   name: Apply tag ${{ needs.calculate-tag.outputs.tag }}
  #   runs-on: ubuntu-22.04
  #   needs: calculate-tag
  #   environment: tagging
  #   outputs:
  #     tag: ${{ steps.set-tag.outputs.new_tag }}
  #   steps:
  #     - name: Apply Tag
  #       id: set-tag
  #       uses: mathieudutour/github-tag-action@v6.1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         custom_tag: ${{ needs.calculate-tag.outputs.tag }}
  #         create_annotated_tag: true
  #         tag_prefix: ''

  #     - name: Get review comments
  #       id: review
  #       uses: ambilykk/deployment-review-comment@main
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Display review comment
  #       uses: actions/github-script@v6
  #       with:
  #         script: |
  #           for(const data of ${{ steps.review.outputs.comments }}){
  #             console.log(data)
  #           }

  set-tag-custom:
    name: Set custom tag
    runs-on: ubuntu-22.04
    needs:
      - calculate-tag
      - apply-tag
    if: needs.apply-tag.outputs.outcome != 'success'
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Set tag to outputs
        id: set-tag
        run: |
          echo ${{ steps.review.outputs.comments }}
          echo ${{ steps.review.outputs.comments[0].comment }}
          echo "tag=test" >> "$GITHUB_OUTPUT"

  apply-tag-custom:
    name: Apply custom tag ${{ needs.set-tag-custom.outputs.tag }}
    runs-on: ubuntu-22.04
    needs: set-tag-custom
    if: needs.set-tag-custom.outputs.outcome != 'success'
    continue-on-error: true
    environment: tagging
    steps:
      - name: Apply Tag
        id: set-tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.set-tag-custom.outputs.tag }}
          create_annotated_tag: true
          tag_prefix: ''
          dry_run: true
